### ISSUE TITLE
Import custom project

### ISSUE THREAD

**Issue by lesto** [elmot/clion-embedded-arm#107] opened 2018-07-12 07:27 UTC
## Expected Behavior
I would like to set OpenOCD as described in the step procedure, even if i did NOT import the project from CubeMX

## Actual Behavior
![image](https://user-images.githubusercontent.com/810910/42618460-58f17e94-85b5-11e8-8804-7602db286416.png)

## Steps to Reproduce the Problem

  1. create your own CMakeList without using CubeMX (existing project)
  1. import the project into CLion
  1. try to set up the OpenOCD settings

## Specifications

  - Plugin Version: 1.1alpha4
  - CLion version: 2018.1.15
  - OpenOCD version: -
  - GDB Version: 7-2017-q4-major (ARM official toolchain)
  - STM32CubeMX version: none
  - Toolchain: 7-2017-q4-major (ARM official toolchain)
  - Platform: windows
  - Hardware configuration: ??

**Comment by elmot** [comment] 2018-07-12 18:32
You may do that already. OpenOCD support and CubeMX support are independent parts of the plugin, and they may be used separately.
Steps to do:
- Setup arm toolchain and the plugin in CLion
- Make a new project and write your own `CMakeLists.txt` for it. The template of the file might be borrowed from [here](https://github.com/elmot/clion-embedded-arm/blob/master/resources/xyz/elmot/clion/cubemx/tmpl_CMakeLists.txt). Note! Cmake build should generate hex file named *cmake-build-debug/&lt;project-name&gt;.hex*.
-  Write your own linker script for used MCU ([example for stm32f407VGTx](https://github.com/elmot/f4-blog/blob/master/STM32F407VGTx_FLASH.ld)).
- Reset CMake caches in CLion.
- Select  or write your own board config file.
- Create `Run Configuration` of type `OpenOCD Download & Run`, set the board config and project's output .elf file as both target and executable, set your board config file
- Start writing your code

**Comment by lesto** [comment] 2018-07-13 10:51
* Setup arm toolchain and the plugin in CLion

what do you mean exactly? i use WSL/minwg toolchain and i override the compiler with -DCMAKE_TOOLCHAIN_FILE=gcc.cmake, is this correct?

* Cmake build should generate hex file named cmake-build-debug/<project-name>.hex.

is cmake-build-debug mandatory (just to know, i'm fine with that, i will just copy the executable there)

**Comment by elmot** [comment] 2018-07-13 13:13
> Setup arm toolchain and the plugin in CLion
> what do you mean exactly? i use WSL/minwg toolchain and i override the compiler with -DCMAKE_TOOLCHAIN_FILE=gcc.cmake, is this correct?
 
I have got rid of toolchain files, I just redefine all the required tools in
CmakeLists,  like [here](https://github.com/elmot/clion-embedded-arm/blob/c6d10b523124e2ad392fe996cf8f8b4c860ee5f7/resources/xyz/elmot/clion/cubemx/tmpl_CMakeLists.txt#L6-L14). On the other hand it's better to find Toolchains in CLion settings, add and manually define your own toolchain with compilers and linker there. And set it as topmost one (i.e. default for your project)

> build should generate hex file named cmake-build-debug/.hex.
> is cmake-build-debug mandatory (just to know, i'm fine with that, i will just copy the executable there)

Oops. Forget it, I had a wrong recollection. The plugin expects the only .elf file to be defined and exists. .hex added to cmake script only for convenience.

Actually I managed to do such a project for non-stm chip, but I have no example to show that.

**Comment by lesto** [comment] 2018-07-16 08:02
Thanks, I just managed to make it sort of work.
The OpenOCD view is the same, just have make sure to use the correct arm gdb, and then the opencodc cobnfiguration is the trick.

Now i have another issue: I'm on windows and my absolute path to the elf contain spaces, and seems like the path is not correctly escaped. Any temporary solution (beside move the project)?

**Comment by elmot** [comment] 2018-07-16 09:23
Not really. If you look at the documentation, I noticed it there. 
You can try to use shortened path but it looks like copying of the project is gonna be much easier.

**Comment by lesto** [comment] 2018-07-16 09:55
so it will not be fixed? is there any specific issue?

**Comment by elmot** [comment] 2018-07-16 09:58
No promises, sorry. I tried once, and I failed, i might try again at some point. There are multiple issues with utilities commands, also it may depend of the platform.

**Comment by lesto** [comment] 2018-07-16 10:49
sorry if i continue here instead of opening new issue, but since this is a custom config I want to double check if it is my error :) Move to a folder without path, and now it upload the firmware and if i "pause" i get current place in code (assembly), but breakpoint does not work. but in the GDB folder i get
"No source file named d:/git projects/test/main.c."
notice here I am using a drive that is not C:, if that matter, but the printed path seems to be correct and existing.. maybe an issue with WSL?

**Comment by elmot** [comment] 2018-07-16 12:20
Try to clear and recompile. Looks like old elf was left untouched, and gdb can not find the original source file from debug info there
.

**Comment by lesto** [comment] 2018-07-16 14:36
i switch to minWG and same issue. I recompiled all and the problem persist.. is there a way to see the command send from the plugin to openocd?

**Comment by elmot** [comment] 2018-07-16 20:29
I do not think it's because of opeoncd, most probably it's because of gdb.
OpenOCD: press `Alt-4`, There is `OpenOCD console` tab. The whole command line is on the very top
gdb: press `Alt-5`, click `Debugger` tab, then `GDB` sub tab, type `info files` + Enter int GDB's input prompt, gdb will what files are loaded. Commands `info source` and `info sources` are also quite useful

**Comment by elmot** [comment] 2019-03-25 10:07
Closed as not a bug. If the issue is still valid, please [create a feature request at JetBrains YouTrack system](https://youtrack.jetbrains.com/newIssue?project=CPP&c=Type%20Task&c=Subsystem%20Embedded).

**Closed by elmot** 2019-03-25 10:07 UTC
Labels: documentation
