### ISSUE TITLE
Load Project Setting Error after add OpenOCD configuration

### ISSUE THREAD

**Issue by MarkCL** [elmot/clion-embedded-arm#131] opened 2018-12-04 01:52 UTC
## Expected Behavior
Project Setting Load OK.

## Actual Behavior
<img width="944" alt="2018-12-04 9 42 33" src="https://user-images.githubusercontent.com/45579538/49413113-ca473c80-f7a9-11e8-9701-b8b52d481474.png">

## Steps to Reproduce the Problem

  1.  Run->Edit Configurations->Add New Configuration choose OpenOCD Download & Run
  2. Click Apply and OK
  3. Restart CLion
  4. Project Setting Load error.

## Specifications

  - Plugin Version:  1.2 alpha
  - CLion version:   2018.3
  - OpenOCD version: 0.10.0
  - GDB Version:    8.0.1
  - STM32CubeMX version:
  - Toolchain:         gcc-arm-none-eabi-7-2018-q2-update
  - Platform: Mac OSX 10.14
  - Hardware configuration:

**Comment by pmahot** [comment] 2018-12-04 08:18
Hi,

This looks like a Duplicate of #123 

Regards,
Pierre

**Comment by elmot** [comment] 2018-12-04 13:58
Duplicate #123

**Comment by MarkCL** [comment] 2018-12-05 05:18
Hi Elmot,

It is duplicate #123, but the issue is back in the latest version CLion 2018.3 and plugin 1.2 alpha 2.
Do you have plan to fix it?
Thanks in advance!

Best Regards,

Mark

**Comment by elmot** [comment] 2018-12-05 07:17
Yes, I am working on it
Duplicate https://youtrack.jetbrains.com/issue/CPP-14863

**Closed** 2018-12-05 14:13 UTC
